import os
import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from odoo_client import OdooClient
from audit_logger import audit

logger = logging.getLogger('CEOBriefing')
VAULT_PATH = Path(os.getenv('VAULT_PATH', './AI_Employee_Vault'))

SUBSCRIPTION_PATTERNS = {
    'netflix.com': 'Netflix',
    'spotify.com': 'Spotify',
    'adobe.com': 'Adobe Creative Cloud',
    'notion.so': 'Notion',
    'slack.com': 'Slack',
    'github.com': 'GitHub',
    'openai.com': 'OpenAI',
    'anthropic.com': 'Anthropic Claude'
}

def get_done_items_this_week() -> list:
    done_folder = VAULT_PATH / 'Done'
    one_week_ago = datetime.now() - timedelta(days=7)
    items = []
    for f in done_folder.glob('*.md'):
        if datetime.fromtimestamp(f.stat().st_mtime) > one_week_ago:
            items.append({'name': f.name, 'content': f.read_text()})
    return items

def get_accounting_data() -> dict:
    accounting_file = VAULT_PATH / 'Accounting' / 'Current_Month.md'
    if not accounting_file.exists():
        return {'income': 0, 'expenses': 0, 'net': 0}
    content = accounting_file.read_text()
    return {'raw': content}

def get_odoo_data() -> dict:
    try:
        client = OdooClient()
        invoices = client.get_invoices(state='posted')
        draft_invoices = client.get_invoices(state='draft')
        expenses = client.get_expenses()
        total_invoiced = sum(inv.get('amount_total', 0) for inv in invoices)
        return {
            'posted_invoices': len(invoices),
            'draft_invoices': len(draft_invoices),
            'total_invoiced': total_invoiced,
            'expenses': len(expenses)
        }
    except Exception as e:
        logger.warning(f'Odoo unavailable: {e}')
        return {'error': str(e)}

def analyze_subscriptions(accounting_data: dict) -> list:
    flags = []
    raw = accounting_data.get('raw', '')
    for pattern, name in SUBSCRIPTION_PATTERNS.items():
        if pattern in raw.lower():
            flags.append({
                'service': name,
                'reason': 'Found in accounting records — verify usage',
                'action': 'Review and confirm still needed'
            })
    return flags

def generate_briefing():
    now = datetime.now()
    week_start = (now - timedelta(days=7)).strftime('%Y-%m-%d')
    week_end = now.strftime('%Y-%m-%d')

    done_items = get_done_items_this_week()
    accounting_data = get_accounting_data()
    odoo_data = get_odoo_data()
    subscription_flags = analyze_subscriptions(accounting_data)

    goals_file = VAULT_PATH / 'Business_Goals.md'
    goals_content = goals_file.read_text() if goals_file.exists() else 'No goals file found.'

    briefing_content = f'''---
generated: {now.isoformat()}
period: {week_start} to {week_end}
---

# Monday Morning CEO Briefing
*Generated by AI Employee — Review Required*

## Executive Summary
Week reviewed: {week_start} to {week_end}
Tasks completed: {len(done_items)}
Odoo invoices (posted): {odoo_data.get("posted_invoices", "N/A")}
Odoo invoices (draft): {odoo_data.get("draft_invoices", "N/A")}

## Revenue
- Total Invoiced (Odoo): ${odoo_data.get("total_invoiced", 0):,.2f}
- Expenses Logged: {odoo_data.get("expenses", 0)} records
- See /Accounting/Current_Month.md for full breakdown

## Completed This Week ({len(done_items)} tasks)
{chr(10).join(f"- [x] {item['name'].replace('.md', '')}" for item in done_items) if done_items else "- No completed tasks found"}

## Subscription Audit
{chr(10).join(f"- ⚠️ **{flag['service']}**: {flag['reason']}" for flag in subscription_flags) if subscription_flags else "- No subscription flags this week"}

## Proactive Suggestions
- Review {len(subscription_flags)} subscription(s) flagged above
- {len(odoo_data.get("draft_invoices", 0) or 0)} draft invoices pending review in Odoo
- Check /Pending_Approval/ for any awaiting items

## Goals Progress
{goals_content[:500]}...

---
*AI Employee v1.0 — Gold Tier*
*All figures should be verified before decisions are made*
'''

    briefings_dir = VAULT_PATH / 'Briefings'
    briefings_dir.mkdir(parents=True, exist_ok=True)
    filename = f'{now.strftime("%Y-%m-%d")}_Monday_Briefing.md'
    briefing_file = briefings_dir / filename
    briefing_file.write_text(briefing_content)
    logger.info(f'CEO Briefing generated: {filename}')

    dashboard = VAULT_PATH / 'Dashboard.md'
    if dashboard.exists():
        content = dashboard.read_text()
        update_line = f'\n- [{now.strftime("%Y-%m-%d")}] CEO Briefing generated → /Briefings/{filename}'
        content = content.replace('_No activity yet._', update_line)
        dashboard.write_text(content)

    audit.log('ceo_briefing', 'ceo_briefing_generator', str(briefing_file),
              {'period': f'{week_start} to {week_end}', 'tasks': len(done_items)},
              'auto', 'success', 'system')

    return briefing_file

if __name__ == '__main__':
    result = generate_briefing()
    print(f'Briefing saved: {result}')
